#!/bin/sh

[ -z "$1" ] && echo "No brightness provided" && exit 1

# echo "delta: $1"

BRIGHTNESS=`xrandr --verbose | grep -m 1 -i brightness | cut -f2 -d ' '`

# echo "current: $BRIGHTNESS"

new=$(echo "$1 + $BRIGHTNESS"  | bc -l)

# echo "new: $new"

xrandr --output eDP-1 --brightness $new

