#!/bin/sh

alias g=git
alias v=vifmrun
alias l='fd --hidden --no-ignore --max-depth 1 .'
alias L='ls -lAFh'
alias o='handlr open'

alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ls='ls --color=always'

alias me='make edit'
alias mi='sudo make install'
alias mic='sudo make install && make clean'

alias mkenv='virtualenv -p "$(which python3)" .env'
alias stenv='source .env/bin/activate'
alias stopenv=deactivate

alias tf=terraform
alias tfi='terraform init'
alias tfp='terraform plan'
alias tfa='terraform apply -auto-approve'
alias tfpp='terraform plan -out=plan'
alias tfap='terraform apply -auto-approve plan'

alias path='tr : "\n" <<< $PATH'

alias nslookup='getent hosts'

alias ghcid='stack exec -- ghcid --color=always -r'

alias golint='golangci-lint run'

# time a command
timec() {
	start="$(date +%s)"
	$@
	stop="$(date +%s)"
	echo $stop - $start | bc
}

resetgpg() {
	gpg-connect-agent reloadagent /bye
}

setupgpg() {
	gpg-connect-agent reloadagent /bye
	testgpg
}

testgpg() {
	cleartext="$HOME"/sync/passwords/kk
	ciphertext="$HOME"/sync/passwords/kk.gpg
	rm -rf "$cleartext" "$ciphertext"
	echo kk >"$cleartext"
	gpg -qs "$cleartext"
	rm -rf "$cleartext" "$ciphertext"
	echo kk >"$cleartext"
	gpg -qe "$cleartext"
	rm -rf "$cleartext" "$ciphertext"
}
