#!/bin/sh

# vim: set foldmethod=marker:

alias f='fd -H -tf ".*" . | fzf -m --select-1 --preview="bat {}" | xargs -r nvim -p'
alias F='fd -H -tf ".*" ~ | fzf -m --select-1 --preview="bat {}" | xargs -r nvim -p'
alias d='cd "$(fd -H -td ".*" . | fzf --select-1)"'
alias D='cd "$(fd -H -td ".*" ~ | sed "s|$HOME|~|g" | fzf --select-1 | sed "s|~|$HOME|g")"'
alias g='git'
alias l='fd -HId1 .'
alias L='ls -AlFh'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'

alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ls='ls --color=always'

alias mi='sudo make install'
alias mic='sudo make install && make clean'

alias mkenv='virtualenv -p $(which python3) .env'
alias stenv='source .env/bin/activate'
alias killenv='deactivate'

alias tf='terraform'
alias tfi='terraform init'
alias tfp='terraform plan -out=out'
alias tfa='terraform apply out'

alias path='tr ":" "\n" <<< $PATH'
