#!/bin/zsh

export FZF_DEFAULT_COMMAND='echo I have disabled the default command feature'
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS"' --reverse --height=99% --exit-0'
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS"' --bind=esc:yank --bind=up:yank --bind=down:yank'
# export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS"' --bind=ctrl-e:down'
# export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS"' --bind=tab:up'
# export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS"' --bind=ctrl-i:up'
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS"' --color=fg:#a89984,bg:#1d2021,hl:#83a598 --color=fg+:#ebdbb2,bg+:#1d2021,hl+:#83a598 --color=info:#afaf87,prompt:#cc241d,pointer:#d3869b --color=marker:#8ec07c,spinner:#1d2021,header:#83a598'

select-history() {
	fc -rl 1 |
		perl -ne 'print if !$seen{(/^\s*[0-9]+\**\s+(.*)/, $1)}++' |
		fzf +m -n2..,.. --tiebreak=index --bind=ctrl-r:toggle-sort
}

fzf-history() {
	setopt localoptions noglobsubst noposixbuiltins pipefail no_aliases 2>/dev/null
	local num="$(select-history)"
	local ret=$?
	[ -n "$num" ] && zle vi-fetch-history -n $num
	zle reset-prompt
	return $ret
}
zle -N fzf-history
bindkey '^R' fzf-history

# TODO: handle special characters like single quotes and double quotes
rename-format() {
	[ -n "$1" ] && {
		maxlen="$(wc -L <<<"$1")"
		while read line; do
			padding="$((maxlen - ${#line} + 1))"
			printf "mv '%s'" "$line"
			[ "$padding" -gt 0 ] && printf ' %.0s' {1..$padding}
			printf "'%s'\n" "$line"
		done <<<"$1"
	}
}

zsh-rename() {
	setopt localoptions pipefail no_aliases 2>/dev/null
	LBUFFER="$(rename-format "$(fd -HI -d1 -tf '.*' . | fzf -m --select-1)")"
	[ -n "$LBUFFER" ] && zle edit-command-line
	zle reset-prompt
}
# in vi normal mode, type :mv
zle -N zsh-rename
# or just use this alias
alias r='vared -i zsh-rename -c kk'
