#!/bin/zsh

KEYTIMEOUT=20

bindkey -v
bindkey -s jk "\e"

# use beam shape cursor on startup
echo -ne "\e[5 q"

# use beam shape cursor for each new prompt
preexec() {
	echo -ne "\e[5 q"
}

# use beam shape cursor on zle startup
zle-line-init() {
	echo -ne "\e[5 q"
}
zle -N zle-line-init

# change cursor shape for different vi modes
zle-keymap-select() {
	[[ "$KEYMAP" = vicmd ]] || [[ "$1" = block ]] &&
		echo -ne "\e[1 q"

	[[ "$KEYMAP" = main ]] || [[ "$KEYMAP" = viins ]] || [[ "$KEYMAP" = '' ]] ||
		[[ "$1" = beam ]] &&
		echo -ne "\e[5 q"
}
zle -N zle-keymap-select
