#!/bin/bash

# shortcut file locations
shell_shortcuts="$HOME/.bash_shortcuts"
vifm_shortcuts="$HOME/.config/vifm/vifm_shortcuts"
ranger_shortcuts="$HOME/.config/ranger/ranger_shortcuts"

# remove existing files
rm "$shell_shortcuts" "$vifm_shortcuts" "$ranger_shortcuts"

# bookmarked folders
printf "\n# bookmarked folders\n\n" >> "$shell_shortcuts"
printf "\n\" bookmarked folders\n\n" >> "$vifm_shortcuts"
printf "\n# bookmarked folders\n\n" >> "$ranger_shortcuts"

# Format the `bmdirs` file in the correct syntax and sent it to all three configs.
sed "s/\s*#.*$//;/^\s*$/d" "$HOME/.config/bmdirs" | tee >(awk '{print "alias g"$1"=\"cd "$2"\""}' >> "$shell_shortcuts") \
	>(awk '{print "map g" $1, ":cd", $2 "<CR>\nmap t" $1, "<tab>:cd", $2 "<CR><tab>\nmap M" $1, "<tab>:cd", $2 "<CR><tab>:mo<CR>\nmap Y" $1, "<tab>:cd", $2 "<CR><tab>:co<CR>" }' >> "$vifm_shortcuts") \
	| awk '{print "map g"$1" cd "$2"\nmap t"$1" tab_new "$2"\nmap m"$1" shell mv -v %s "$2"\nmap Y"$1" shell cp -rv %s "$2}' >> "$ranger_shortcuts"

# bookmarked files
printf "\n# bookmarked files\n\n" >> "$shell_shortcuts"
printf "\n\" bookmarked files\n\n" >> "$vifm_shortcuts"
printf "\n# bookmarked files\n\n" >> "$ranger_shortcuts"

# Format the `configs` file in the correct syntax and sent it to both configs.
sed "s/\s*#.*$//;/^\s*$/d"  "$HOME/.config/bmfiles" | tee >(awk '{print "alias "$1"=\"$EDITOR "$2"\""}' >> "$shell_shortcuts") \
	>(awk '{print "map", $1, ":e", $2 "<CR>" }' >> "$vifm_shortcuts") \
	| awk '{print "map "$1" shell $EDITOR "$2}' >> "$ranger_shortcuts"


printf "\n" >> "$shell_shortcuts"
printf "\n" >> "$vifm_shortcuts"
printf "\n" >> "$ranger_shortcuts"

