#!/bin/bash

DIR=~/.local/dotfiles

declare -a StringArray=( \

	.gitconfig \
	.xinitrc \
	.zshenv \

	.config/bmfiles \
	.config/bmdirs \

	.config/dunst/dunstrc \

	.config/nvim/init.vim \
	.config/nvim/ftplugin/json.vim \

	.config/scripts/bt_devices \
	.config/scripts/ff_profiles \

	.config/shell/aliases \
	.config/shell/profile \

	.config/vifm/vifmrc \
	.config/vifm/scripts/vifmimg \

	.config/X/.Xmodmap \
	.config/X/.Xmodmap.default \

	.config/zathura/zathurarc \

	.config/zsh/.zshrc \
	.config/zsh/.zprofile \

	.fonts/FiraMono-Regular.ttf \

)

for val in ${StringArray[@]}
do
	rm ~/$val
	ln -sv $DIR/$val ~/$val
done

