#!/bin/bash

DIR=~/Projects/dotfiles

declare -a StringArray=( \

	.bash_aliases \
	.bashrc \
	.profile \

	.tmux.conf \
	.vimrc \
	.wallpaper \
	.Xresources \

	.config/dunst/dunstrc \
	.config/i3/config \
	.config/i3/polybar.sh \
	.config/mutt/colors.muttrc \
	.config/mutt/muttrc \
	.config/polybar/config \
	.config/vifm/vifmrc \
	.config/zathura/zathurarc \

	.vim/ftplugin/python.vim \
	.vim/ftplugin/json.vim \
	.vim/ftplugin/markdown.vim \
)

for val in ${StringArray[@]}
do
	rm ~/$val
	ln -sv $DIR/$val ~/$val
done

