vim.cmd [[augroup format ]]
vim.cmd [[autocmd! ]]
vim.cmd [[autocmd BufWritePost * lua require("kesav.formatter").format() ]]
vim.cmd [[augroup END ]]

vim.cmd [[ augroup misc ]]
vim.cmd [[ autocmd! ]]
-- vim.cmd [[ autocmd BufWritePre * %s/\s\+$//e ]]
vim.cmd [[ autocmd BufWritePost *dunstrc silent !killall -q dunst; dunst & ]]
vim.cmd [[ autocmd BufWritePost *sxhkdrc silent !pkill -USR1 sxhkd ]]
vim.cmd [[ autocmd BufWritePost *sxhkdrc.personal silent !pkill -USR1 sxhkd ]]
vim.cmd [[ autocmd BufWritePost *bspwmrc silent !source % ]]
-- vim.cmd [[ autocmd BufWritePost *launchlemonbar silent !killall -q lemonbar; % & ]]
vim.cmd [[ autocmd TextYankPost * silent! lua require('vim.highlight').on_yank { higroup = 'Visual', timeout = 250 } ]]
vim.cmd [[ autocmd BufWritePost plugins.lua PackerCompile ]]
vim.cmd [[ augroup END ]]
