#!/bin/sh

# vim: set foldmethod=marker:

alias f='fzf -m --preview="bat {}" | xargs -r nvim -p'
# alias b='cd $XDG_BIN_DIR && v && cd - >/dev/null'
# alias d='cd $XDG_DOTFILES_DIR && v && cd - >/dev/null'
alias o='vifmu . ~ && cd "$(< "$XDG_CONFIG_HOME"/vifm/lastdir)"'
alias g=git

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'

alias ll='ls -AlF --color=always'

alias mdc='pandoc -s -t html5 --pdf-engine=wkhtmltopdf --katex'

alias mi='sudo make install'
alias mic='sudo make install && make clean'

alias mkenv='virtualenv -p $(which python3) .env'
alias stenv='source .env/bin/activate'
alias killenv='deactivate'

alias tf='terraform'
alias tfi='terraform init'
alias tfp='terraform plan -out=out'
alias tfa='terraform apply out'

alias path='echo ${PATH//:/\\n}'
