#!/bin/sh

# vim: set foldmethod=marker:

echo "sourced aliases"

# misc {{{

alias ..="cd .."

v() {
	# fd --hidden --follow --type f --max-depth 2 \
	fd --hidden --follow --type f \
		-E '*.pdf' -E '*.epub' -E '*.opf' \
		-E '*.webm' -E '*.png' -E '*.jpg' \
		-E '*.db' -E '*.tdb' -E '*.sqlite' \
		-E '*.o' -E '*.pkl' -E '*.tar' \
		-E '.git' -E '__pycache__' -E '.pytest_cache' -E '.env' \
		| fzf --multi --preview="bat {}" \
		| xargs -r nvim

}

alias vf="vifmu . ~"
alias ll="ls -AlF --color=always"
alias xm="xmodmap $(readlink -f "$XDG_CONFIG_HOME"/X11/xmodmaprc)"

alias me="monctl --extend"
alias md="monctl --disconnect"

alias mi="sudo make install"
alias mic="sudo make install && make clean"

alias vc='virtualenv --no-site-packages -p $(which python3) .env'
alias va="source .env/bin/activate"
alias vd="deactivate"

# compile latex file and delete output files (except for pdf)
lc() {
	pdflatex $1
	pdflatex $1
	rm *.log
	rm *.aux
	rm *.toc
}

# print out path neatly
path() {
	echo "$PATH" | tr ':' '\n'
}

# }}}

# packages {{{

# pacman -Slq | fzf -m --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S
# pacman -Q | awk '{print $1}' | fzf -m --preview 'pacman -Qi {1}'
# pac_list | xargs -ro sudo pacman -Rns
# yay -Slq | fzf -m --preview 'yay -Si {1}'| xargs -ro yay -S

# }}}

# git {{{

alias gis="clear && git status"
alias gic="git commit -S"
alias gids="git diff --staged"
alias gip="git push"

# branching

alias mkb='git checkout -b'
alias delb='git branch -d'

mergeb() {
	branch=$(git branch | awk '/\*/ {print $2}')
	git checkout master && git merge "$branch"
}

useb() {
	git branch | awk '{print $2}' | fzf | xargs -r -I b git checkout b
}

# }}}
