#!/bin/sh

# vim: set foldmethod=marker:

echo "sourced aliases"

# misc {{{

alias ..="cd .."

alias v='fzf -m --preview="bat {1}" | xargs -r nvim'
alias vf="vifmu . ~"
alias ll="ls -AlF --color=always"
alias xm="xmodmap $(readlink -f "$XDG_CONFIG_HOME"/X11/xmodmaprc)"

alias me="monctl --extend"
alias md="monctl --disconnect"

alias mi="sudo make install"
alias mic="sudo make install && make clean"

alias vc='virtualenv --no-site-packages -p $(which python3) .env'
alias va="source .env/bin/activate"
alias vd="deactivate"

# compile latex file and delete output files (except for pdf)
lc() {
	pdflatex $1
	pdflatex $1
	rm *.log
	rm *.aux
	rm *.toc
}

# get size of directory
dirsize () {
	du -h --max-depth=1 | sort -hr
}

# print out path neatly
path () {
	sed 's/:/\n/g' <<< "$PATH"
}

# reload Xresources
refresh () {
	xrdb -merge ~/.Xresources
	exit
}

# }}}

# git {{{

alias gis="clear && git status"
alias gic="git commit -S"

# git checkout branch
gich() {
	local branches branch
	branches=$(git --no-pager branch -vv) &&
	branch=$(echo "$branches" | fzf +m) &&
	git checkout $(echo "$branch" | awk '{print $1}' | sed "s/.* //")
}

alias gichm="git checkout master"
alias gim="git merge"
alias gib="git branch"
alias gip="git push"

# git view staged changes
alias gids="git diff --staged"

# }}}

