#!/bin/sh

echo "sourced profile"

# set system env variables

export EDITOR=/usr/bin/nvim
export PASSWORD_STORE_DIR=/home/kesav/.config/pass/
export BAT_THEME="Gruvbox-N"
export ZPLUG_HOME="$HOME/.local/src/zplug"

# set my env variables

export ICONPATH="$HOME/.icons/fa-5.10.2-desktop"
export SCRIPTSPATH="$HOME/.local/scripts"
export BINPATH="$HOME/.local/bin"

# add local scripts to PATH

bin_in_path=$(echo "$PATH" | grep "$BINPATH")
# if bin is not in path, add bin to path
[ -z "$bin_in_path" ] && PATH="$PATH:$BINPATH"

# set colored output

alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ls='ls --color=always'

# colored man pages

# export LESS=-R
# export LESS_TERMCAP_mb="$(printf '%b' '')"
# export LESS_TERMCAP_md="$(printf '%b' '')"
# export LESS_TERMCAP_me="$(printf '%b' '')"
# export LESS_TERMCAP_so="$(printf '%b' '')"
# export LESS_TERMCAP_se="$(printf '%b' '')"
# export LESS_TERMCAP_us="$(printf '%b' '')"
# export LESS_TERMCAP_ue="$(printf '%b' '')"

# set up node version manager
export NVM_DIR="$HOME/.nvm"                            # You can change this if you want.
export NVM_SOURCE="/usr/share/nvm"                     # The AUR package installs it to here.
[ -s "$NVM_SOURCE/nvm.sh" ] && . "$NVM_SOURCE/nvm.sh"  # Load NVMource /usr/share/nvm/init-nvm.sh

# set up fzf

# export FZF_DEFAULT_COMMAND='find .'
export FZF_DEFAULT_COMMAND='find . -type f | grep -v '\.git/' | grep -v '__pycache__/' | grep -v '\.pytest_cache' | grep -v '\.env''

export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS' --reverse'
export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS' --color=fg:#a89984,bg:#282828,hl:#83a598 --color=fg+:#ebdbb2,bg+:#262626,hl+:#83a598 --color=info:#afaf87,prompt:#cc241d,pointer:#d3869b --color=marker:#8ec07c,spinner:#d3869b,header:#83a598'

# start x

if systemctl -q is-active graphical.target && [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]
then
	exec startx
fi

export GPG_TTY=$(tty)

