#!/bin/sh

# clear cache on startup
[ -d "$XDG_CACHE_HOME"/bin ] &&
	rm -rf "$XDG_CACHE_HOME"/bin &&
	mkdir "$XDG_CACHE_HOME"/bin

# clear vifm Trash cache
[ -d "$XDG_DATA_HOME"/vifm/Trash ] &&
	rm -rf "$XDG_DATA_HOME"/vifm/Trash &&
	mkdir "$XDG_DATA_HOME"/vifm/Trash

hsetroot -solid '#1d2021'      # set wallpaper
xsetroot -cursor_name left_ptr # set cursor

xset dpms 0 0 0
xset s 0 0

# xset dpms 600 600 600
# xset s 570 15
# xss-lock -n dimscreen -- slock &

# start with colemak config
touch "$XDG_CACHE_HOME"/bin/colemak
# bind keys
sxhkd "$XDG_CONFIG_HOME"/sxhkd/sxhkdrc.personal \
	"$XDG_CONFIG_HOME"/sxhkd/sxhkdrc.colemak >"$XDG_CACHE_HOME"/bin/sxhkd 2>&1 &
# notification daemon
dunst >"$XDG_CACHE_HOME"/bin/dunst 2>&1 &
# compositor
picom --no-vsync -b --log-file "$XDG_CACHE_HOME"/bin/picom
# hide cursor after five seconds
unclutter --fork

# sudo updatepackages >"$XDG_CACHE_HOME"/bin/updatepackages 2>&1 &
# pamonitor >>"$XDG_CACHE_HOME"/bin/pamonitor 2>&1 &
launchbar >"$XDG_CACHE_HOME"/bin/launchbar 2>&1 &
exec bspwm -c "$XDG_CONFIG_HOME"/bspwm/bspwmrc
