#!/bin/sh

# clear cache on startup
[ -d "$XDG_CACHE_HOME"/bin ] &&
	rm -rf "$XDG_CACHE_HOME"/bin &&
	mkdir "$XDG_CACHE_HOME"/bin

hsetroot -solid '#1d2021' # set wallpaper

xset -dpms
xset s 0 0

# xset dpms 300 300 300
# xset s 180 10
# xss-lock -n dimscreen -- slock &

# bind keys
sxhkd "$XDG_CONFIG_HOME"/sxhkd/sxhkdrc.personal >"$XDG_CACHE_HOME"/bin/sxhkd 2>&1 &
# notification daemon
dunst >"$XDG_CACHE_HOME"/bin/dunst 2>&1 &
# compositor
picom --no-vsync -b --log-file "$XDG_CACHE_HOME"/bin/picom

# sudo updatepackages >"$XDG_CACHE_HOME"/bin/updatepackages 2>&1 &
unbuffer sinkmon >>"$XDG_CACHE_HOME"/bin/sinkmon 2>&1 &
dwmblocks >"$XDG_CACHE_HOME"/bin/dwmblocks 2>&1 &
exec dwmloop
