#!/bin/sh

# set wallpaper
hsetroot -solid "#1d2021"

launchbar &

# split desktops based on monitors
mcount="$(polybar --list-monitors | wc -l)"
if [ "$mcount" -eq 2 ]; then
	bspc monitor 'HDMI-1' -d 1 2 3 4 5 6
	bspc monitor 'eDP-1' -d 7 8 9
else
	bspc monitor 'eDP-1' -d 1 2 3 4 5 6 7 8 9
fi

bspc config automatic_scheme 'alternate'

bspc config normal_border_color '#282828'
bspc config active_border_color '#928374'
bspc config focused_border_color '#689d6a'

bspc config border_width 2
bspc config window_gap 10

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

# bspc rule -a \* node="@/2" split_dir="south"
