#!/bin/sh

# monitors

bspc query --monitors --names | xargs -I{} bspc monitor {} --reset-desktops 1 2 3 4 5 6

# settings

bspc config border_width 3
bspc config window_gap 0
bspc config top_padding 50

bspc config split_ratio 0.50
bspc config removal_adjustment false

bspc config normal_border_color '#504945'
bspc config active_border_color '#504945'
bspc config focused_border_color '#cc241d'

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

# rules

bspc rule --remove '*'
bspc rule --add '*' state=tiled

bspc rule --add zoom:zoom state=floating
bspc rule --add Bspwm:motion_recorder state=floating
bspc rule --add firefox:Firefox state=floating
bspc rule --add firefox:firefox state=floating
bspc rule --add firefox:Toolkit state=floating
bspc rule --add Discord:discord state=floating
bspc rule --add Pavucontrol:pavucontrol state=floating
bspc rule --add st-256color:centered state=floating
bspc rule --add Pinentry-gtk-2:pinentry-gtk-2 state=floating
bspc rule --add Signal-desktop:signal-desktop state=floating # signal download window
bspc rule --add SimpleScreenRecorder:SimpleScreenRecorder state=floating
bspc rule --add Pcmanfm:pcmanfm state=floating

bspc rule --add Lxappearance:lxappearance state=floating

# Nvidia-settings
# nvidia-settings
# Really quit?

# bspc rule --add Signal:signal desktop=5
# bspc rule --add discord:discord desktop=5
# bspc rule --add Slack:slack desktop=5
