#!/bin/sh

# fix cursor
xsetroot -cursor_name left_ptr

# set master/stack layout
stacklayout2 &
bspc config external_rules_command "$(which bspwmrules)"

# other settings

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action3 resize_corner

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc config split_ratio 0.50
bspc config removal_adjustment false

bspc config normal_border_color '#282828'
bspc config active_border_color '#504945'
bspc config focused_border_color '#a89984'

bspc config border_width 2
bspc config window_gap 5

# window rules

bspc rule -a '*:*' state=tiled
bspc rule -a 'Pinentry-gtk-2:pinentry-gtk-2' state=floating
bspc rule -a 'Wicd-client.py:wicd-client.py' state=floating
bspc rule -a 'Pavucontrol:pavucontrol' state=floating
bspc rule -a 'zoom:zoom' state=floating
bspc rule -a 'Discord:discord' state=floating
bspc rule -a 'Kazam:kazam' state=floating
bspc rule -a 'jetbrains-toolbox:JetBrains Toolbox' state=floating
bspc rule -a 'Bspwm:motion_recorder' state=floating

bspc rule -a 'st-256color:fzfmenu' state=floating
bspc rule -a 'st-256color:stclock' state=fullscreen

bspc rule -a 'jetbrains-clion:jetbrains-clion' state=floating
bspc rule -a 'jetbrains-pycharm:jetbrains-pycharm' state=floating
bspc rule -a 'jetbrains-webstorm:jetbrains-webstorm' state=floating
bspc rule -a 'Code:code' state=floating

# open first instance as tiled
bspc rule -a 'jetbrains-clion:jetbrains-clion' -o state=tiled
bspc rule -a 'jetbrains-pycharm:jetbrains-pycharm' -o state=tiled
bspc rule -a 'jetbrains-webstorm:jetbrains-webstorm' -o state=tiled
bspc rule -a 'Code:code' -o state=tiled

bspc rule -a 'firefox:Firefox' state=floating
bspc rule -a 'firefox:firefox' state=floating
bspc rule -a 'firefox:Toolkit' state=floating

# polybar

# split desktops based on monitors
if [ "$(polybar -m | wc -l)" -eq 2 ]; then
	bspc monitor 'HDMI-1' -d 1 2 3 4 5 6
	bspc monitor 'eDP-1' -d 7 8 9
else
	bspc monitor 'eDP-1' -d 1 2 3 4 5 6 7 8 9
fi

# launch polybar after settings monitors
launchbar &
